title = "jinyuz.dev"

[params.author]
name = "@yujinyuz"
image = "img/avatar.jpg"
headline = "Software Engineer"
bio = "Terminerd"
links = [
  { linkedin = "https://linkedin.com/in/yujinyuz" },
  { github = "https://github.com/yujinyuz" },
  { twitter = "https://twitter.com/yujinyuz_" },
  { instagram = "https://instagram.com/yujinyuz" },
  { email = "mailto:hello@jinyuz.dev" },
]
