[[main]]
name = "/ posts"
pageRef = "posts"
weight = 10


[[main]]
name = "/ about"
pageRef = "about"
weight = 20

[[main]]
name = "/ uses"
pageRef = "uses"
weight = 30

[[main]]
name = "/ logs"
pageRef = "logs"
