[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "Weekly Journal"
pageRef = "weekly-journal"
weight = 15


[[main]]
name = "Uses"
pageRef = "uses"
weight = 20

[[main]]
name = "About Me"
pageRef = "about"
weight = 30
