colorScheme = "ocean"

enableSearch = false
enableCodeCopy = true
attribution = false


[homepage]
layout = "profile"
showRecent = false

[article]
showDate = true
showDateUpdated = true
showAuthor = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = true
editURL = "https://github.com/yujinyuz/jinyuz.dev/tree/master/content/"
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = true
showComments = true
sharingLinks = ["facebook", "x-twitter", "reddit", "linkedin"]

[list]
showBreadcrumbs = false
showSummary = false
showTableOfContents = false
groupByYear = false

[footer]
showThemeAttribution = false
