[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.119.0"
NODE_ENV = "production"
TZ = "Asia/Manila"

[context.production.environment]
HUGO_ENV = "production"
